# Generated by Django 4.0.1 on 2022-02-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
        migrations.AddField(
            model_name="customer",
            name="first_name",
            field=models.CharField(default="a", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(default="b", max_length=100),
            preserve_default=False,
        ),
    ]
