# Generated by Django 4.0.2 on 2022-03-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_appointments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="appointments",
        ),
    ]
