# Generated by Django 4.0.1 on 2022-02-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_dayandtime", models.DateTimeField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("cell", models.CharField(max_length=100)),
            ],
        ),
    ]
