# Generated by Django 4.0.2 on 2022-02-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_rename_length_schedules_lengthinminutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedules",
            name="LengthInMinutes",
            field=models.IntegerField(),
        ),
    ]
