# Generated by Django 4.0.2 on 2022-03-12 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_remove_customer_appointments"),
        ("schedules", "0004_alter_schedules_lengthinminutes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedules",
            name="cell",
        ),
        migrations.RemoveField(
            model_name="schedules",
            name="name",
        ),
        migrations.AddField(
            model_name="schedules",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
            ),
        ),
    ]
