# Generated by Django 4.0.2 on 2022-03-19 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0006_service_remove_schedules_lengthinminutes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedules",
            name="EndTime",
        ),
    ]
